import { Link } from "react-router-dom"
import TextLink from "../../Components/TextLink"

const info = 
<div className="">
    <p>Versión vigente 04/10/2021</p><br/>
    <p>Este contrato describe los términos y condiciones generales (los "Términos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por Roofstore S.R.L., CUIT 30-70308853-4, ("los Servicios") dentro de los sitios www.Roofstore.com.ar y www.mercadopago.com.ar ("Roofstore" o el "sitio"). Cualquier persona (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales respectivos, junto con todas las demás políticas y principios que rigen Roofstore y que son incorporados al presente por referencia.</p><br/>
    <p><strong>CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</strong></p><br/>
    <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad así como en los demás documentos incorporados a los mismos por referencia, previo a su registración como Usuario de Roofstore, optando de forma expresa por recibir los mismos y toda otra información por medios digitales.</p><br/>
    <h2>01 - Capacidad</h2><br/>
    <p>Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad o Usuarios de Roofstore que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si estás registrando un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.</p><br/>
    <p>Los menores de edad, a partir de los 13 años, sólo podrán utilizar su cuenta con autorización del representante legal, quien responderá por todas las acciones y obligaciones que se deriven de la utilización de esa cuenta y quien. También deberá velar por el uso responsable y adecuado de ella en atención a la madurez del menor de edad que autorice. </p><br/>
    <h2>02 - Registración</h2><br/>
    <p>Es obligatorio completar el formulario de registración en todos sus campos con datos válidos para poder utilizar los servicios que brinda Roofstore. El futuro Usuario deberá completarlo con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. El Usuario presta expresa conformidad con que Roofstore utilice diversos medios para identificar sus datos personales, asumiendo el Usuario la obligación de revisarlos y mantenerlos actualizados. Roofstore NO se responsabiliza por la certeza de los Datos Personales de los Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de sus Datos Personales.</p><br/>
    <p>A su exclusiva discreción, Roofstore podrá requerir una registración adicional a los Usuarios que operen como concesionarias o inmobiliarias, como requisito para que dichos Usuarios accedan a paquetes especiales de publicaciones. En estos casos, una vez efectuada la registración adicional, las ofertas de venta de automóviles o inmuebles que realicen las concesionarias o inmobiliarias, respectivamente, sólo se publicarán en Roofstore a través de alguno de dichos paquetes o bajo las modalidades que Roofstore habilite para este tipo de Usuarios. Roofstore se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, se dará de baja todos los artículos publicados, así como las ofertas realizadas, sin que ello genere algún derecho a resarcimiento.</p><br/>
    <p>El Usuario accederá a su cuenta personal ("Cuenta") mediante el ingreso de su Apodo y clave de seguridad personal elegida ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.</p><br/>
    <p>La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario registre o posea más de una Cuenta. En caso que Roofstore detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelar, suspender o inhabilitarlas.</p>
    <p>El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a Roofstore en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta (incluyendo la reputación) bajo ningún título.</p><br/>
    <p>Roofstore se reserva el derecho de rechazar cualquier solicitud de registración o de cancelar una registración previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p><br/>
    <p><TextLink url={'/'} className={'txt-blue'} children={"Ver políticas de inhabilitación o suspensión de usuario"}></TextLink></p><br/>
    <h2>03 - Modificaciones del Acuerdo</h2><br/>
    <p>Roofstore podrá modificar los Términos y Condiciones Generales en cualquier momento haciendo públicos en el Sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Dichas modificaciones serán comunicadas por Roofstore a los usuarios que en la Configuración de su Cuenta de Roofstore hayan indicado que desean recibir notificaciones de los cambios en estos Términos y Condiciones. Todo usuario que no esté de acuerdo con las modificaciones efectuadas por Roofstore podrá solicitar la baja de la cuenta.</p><br/>
    <p>El uso del sitio y/o sus servicios implica la aceptación de estos Términos y Condiciones generales de uso de Roofstore.</p><br/>
    <h2>04 - Listado de Bienes</h2><br/>
    <h3>4.1 Utilización de RoofPay</h3><br/>
    <p>Al publicar un anuncio en el Sitio, el usuario vendedor consiente expresamente la utilización de RoofPay como una de las formas disponibles para el pago del bien o servicio ofrecido y se obliga a no modificar en nada el precio de venta del bien o servicio si el comprador decidiera utilizar RoofPay. Asimismo, el usuario declara que ha leído, comprendido y aceptado los <TextLink url={'/'} className={'txt-blue'} children={"Términos y Condiciones"}></TextLink> de utilización de dicho servicio.</p><br/>
    <h3>4.2 Publicación de bienes y/o servicios</h3><br/>
    <p>El Usuario deberá ofrecer a la venta los bienes y promover los servicios en las categorías y subcategorías apropiadas. Las publicaciones podrán incluir textos descriptivos, gráficos, fotografías y otros contenidos y condiciones pertinentes para la venta del bien o la promoción del servicio, siempre que no violen ninguna disposición de este acuerdo o demás políticas de Roofstore. El bien o servicio ofrecido por el Usuario vendedor debe ser exactamente descrito en cuanto a sus condiciones y características relevantes. Se entiende y presume que mediante la inclusión del bien o servicio en Roofstore, el Usuario acepta que tiene la intención y el derecho de vender el bien u ofrecer el servicio referido, o está facultado para ello por su titular. Asimismo, el Usuario acepta que tiene disponible el bien publicado para su entrega inmediata o para el plazo especificado en la publicación, así como el servicio para su prestación en el plazo acordado. Se establece que los precios de los bienes o servicios publicados deberán ser expresados con IVA incluido cuando corresponda la aplicación del mismo, y en moneda de curso legal. Roofstore podrá remover cualquier publicación cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del bien o servicio. Se deja expresamente establecido que ninguna descripción podrá contener datos personales o de contacto, tales como, y sin limitarse a, números telefónicos, dirección de e-mail, dirección postal, direcciones de páginas de Internet que contengan datos como los mencionados anteriormente. Para determinados productos, Roofstore podrá requerir al vendedor que también realice su publicación a través de <TextLink url={'/'} className={'txt-blue'} children={"Publicaciones de Catálogo"}></TextLink>.</p><br/>
    <p>En las categorías Autos, Motos y Otros, Inmuebles y Servicios, los datos personales o de contacto deberán agregarse en la sección específicamente prevista para incluir la información sobre el vendedor o anunciante. No podrán publicitarse otros medios de pagos, distintos de los enunciados por Roofstore en la página de publicación de artículos, ni tampoco se podrá sugerir o insinuar a los compradores que no utilicen RoofPay y/o alterar las condiciones de compra si el Usuario comprador decidiera utilizar RoofPay.</p><br/>
    <h3>4.3 Licencia sobre imágenes, fotografías, marcas e Información de Producto</h3><br/>
    <p>El usuario autoriza a Roofstore y sus compañías asociadas a utilizar, publicar, reproducir y/o adaptar las imágenes y fotografías incluidas en sus publicaciones, su nombre comercial, marcas, frases publicitarias, logos, diseños, dibujos, imágenes y todo otro signo distintivo que identifique al Usuario y sus productos o servicios (la "Marca") e información de sus productos o servicios ("Información de Producto"). Será obligación del Usuario incluir en las publicaciones las imágenes, fotografías y Marca, así como la Información de Producto, de manera actualizada, incluyendo aquellas advertencias que sean requeridas por la legislación aplicable para la venta o publicidad de los productos y servicios . Conforme a lo anterior, Roofstore podrá obtener las imágenes, fotografías, Marca e Información de Producto directamente del Usuario, terceros autorizados por éste, o a través del sitio web del Usuario.</p><br/>
    <p>En particular, el Usuario otorga a Roofstore y a sus sociedades relacionadas una autorización gratuita, irrevocable, no exclusiva, internacional y sin límite temporal para usar, publicar, reproducir y/o adaptar las imágenes, fotografías, la Marca y la Información de Producto con el fin de ser usadas en todos los sitios y aplicaciones de Roofstore, redes sociales y/o en cualquier medio masivo y no masivo de comunicación, incluyendo sin limitación, plataformas y cualquier otro medio digital o físico que Roofstore considere oportuno o con aquellas otras plataformas o sitios de Internet con los cuales Roofstore haya realizado una alianza, para identificar ofertas, clasificar productos, crear catálogos, realizar acciones publicitarias y de marketing vinculadas a los servicios de Roofstore, incluyendo la posibilidad de asociación con marcas y/o nombres comerciales de terceros, así como sublicenciar su uso a terceros, incluyendo, de manera enunciativa, más no limitativa, facultades de uso, publicación, reproducción y adaptación de las imágenes, fotografías, Marca e Información de Producto en el marco de las Publicaciones de Catálogo.</p><br/>
    <p>El Usuario declara y garantiza que es titular o licenciatario de los derechos necesarios sobre las imágenes, fotografías contenidas en sus publicaciones, sobre las Marcas, así como sobre la Información de Producto, y que cuenta con los derechos y facultades necesarias para conceder la autorización detallada en esta cláusula, siendo responsable exclusivo por cualquier infracción a derechos de terceros o por las inconsistencias o inexactitud en la Información de Producto.</p><br/>
    <p>Roofstore podrá eliminar la publicación de las imágenes y fotografías, e incluso del bien o servicio, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes Términos y Condiciones. Las imágenes y fotografías de bienes o servicios publicados bajo la modalidad Premium deberán cumplir con algunos requisitos adicionales como condición para ser expuestas en la Página Principal del Sitio Web. <TextLink url={'/'} className={'txt-blue'} children={"Conocé los requisitos"}></TextLink>.</p><br/>
    <h3>4.4 Artículos Prohibidos</h3><br/>
    <p>Sólo podrán ser ingresados en las listas de bienes y servicios ofrecidos, aquellos cuya venta no se encuentre tácita o expresamente prohibida en los Términos y Condiciones Generales y demás políticas de Roofstore o por la ley vigente. Para obtener mayor información sobre bienes o servicios prohibidos, se pueden consultar nuestras <TextLink url={'/'} className={'txt-blue'} children={"Políticas de Artículos Prohibidos"}></TextLink> de Roofstore.</p><br/>
    <h3>4.5 Brand Protection Program</h3><br/>
    <p>Roofstore ha desarrollado un Programa (en adelante, "BPP") destinado a brindar a los titulares de Propiedad Intelectual una herramienta para denunciar contenido en supuesta infracción a sus derechos. Los participantes del BPP, sean los titulares de derechos o sus apoderados, podrán identificar y solicitar la remoción de aquellas publicaciones que infrinjan sus derechos. En caso que Roofstore reciba una denuncia a través del BPP o un reclamo de un tercero o sospeche que se está cometiendo o se ha cometido una infracción a derechos de Propiedad Intelectual, Roofstore se reserva el derecho de adoptar todas las medidas que entienda adecuadas, lo que puede incluir la aplicación de sanciones sobre la cuenta y publicaciones del usuario, como también brindar datos personales del usuario, tal como se describe en las Políticas de Privacidad.</p><br/>
    <p>Los Usuarios entienden y aceptan que la responsabilidad por las denuncias, suspensión y eliminación de publicaciones realizadas a través de BPP es únicamente de los miembros del Programa.</p><br/>
    <p>Al solicitar la adhesión al BPP estarás aceptando los Términos y Condiciones del programa, y la información brindada tendrá carácter de declaración jurada.</p><br/>
    <h2>05 - Privacidad de la Información</h2><br/>
    <p>Para utilizar los Servicios ofrecidos por Roofstore, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se pueden consultar nuestras <TextLink url={'/'} className={'txt-blue'} children={"Políticas de Privacidad"}></TextLink>.</p><br/>
    <h2>06 - Obligaciones de los Usuarios</h2><br/>
    <h3>6.1 Obligaciones del comprador</h3><br/>
    <p>Durante el plazo fijado por el Usuario vendedor, los Usuarios interesados realizarán ofertas de compra para los bienes y servicios que permitan la contratación en el Sitio y podrán contactar a los oferentes de las categorías Autos, Motos y Otros, Inmuebles y Servicios. La oferta de venta se cierra una vez que vence el plazo de la publicación o se acaban las cantidades estipuladas por el Vendedor y la promoción del servicio culmina con el vencimiento del plazo de la publicación.</p><br/>
    <p>El Comprador está obligado a intentar comunicarse con el vendedor y completar la operación si ha realizado una oferta por un artículo salvo que la operación esté prohibida por la ley o los Términos y Condiciones Generales y demás políticas de Roofstore, en cuyo caso no estará obligado a concretar la operación.</p><br/>
    <p>Al ofertar por un bien o contratar un servicio, el Usuario acepta quedar obligado por las condiciones de venta incluidas en la publicación, en la medida en que las mismas no infrinjan las leyes o los Términos y Condiciones Generales y demás políticas de Roofstore. La oferta de compra de un bien o contratación de un servicio es irrevocable salvo en circunstancias excepcionales, tales como que el vendedor cambie sustancialmente la descripción del bien o servicio después de realizada alguna oferta, que exista un claro error tipográfico, o que no pueda verificar la identidad del vendedor.</p><br/>
    <p>Las ofertas de compra sólo serán consideradas válidas una vez que hayan sido procesadas por el sistema informático de Roofstore.</p><br/>
    <p>Ante cualquier inconveniente, el usuario comprador podrá iniciar un reclamo en el Sitio contra su vendedor, dentro de los 60 días de realizada la compra.</p><br/>
    <p><strong>Impuestos</strong>. Tal como lo establece la normativa fiscal vigente, el comprador debe exigir factura o ticket al vendedor como comprobante de la operación. El vendedor no estará obligado a emitir factura o ticket sólo en el caso de tratarse de una persona física que efectúa ventas ocasionalmente.</p><br/>
    <h3>6.2. Obligaciones del vendedor</h3><br/>
    <p>El usuario vendedor debe tener capacidad legal para vender el bien o servicio objeto de su oferta. Asimismo, debe cumplir con todas las obligaciones regulatorias pertinentes y contar con los registros, habilitaciones, permisos y/o autorizaciones exigidos por la normativa aplicable para la venta de los bienes y servicios ofrecidos. Si el usuario vendedor ha recibido una oferta queda obligado a intentar comunicarse con el comprador y completar la operación. La cancelación de una venta por parte del Usuario vendedor impactará en su reputación. Aquel Usuario vendedor que tenga un porcentaje de ventas canceladas igual o superior a 2,5%, podrá ser advertido, suspendido y/o inhabilitado por Roofstore para continuar operando en el sitio.</p><br/>
    <p>Roofstore tendrá el derecho de requerir, conforme los criterios que considere pertinentes, que ciertos usuarios vendedores solamente anuncien sus bienes o servicios en el Sitio Web mediante la utilización de los Servicios de Gestión de Pagos online de RoofPay y/o otras herramientas ofrecidas por Roofstore para el cobro del bien vendido y de las tarifas por la utilización de los servicios, importando eventualmente en el pago de tarifas aplicables por la utilización de los mismos.</p><br/>
    <p>Dado que Roofstore es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el vendedor será responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus bienes y/o servicios, sin que pudiera imputársele a Roofstore algún tipo de responsabilidad por incumplimientos en tal sentido.</p><br/>
    <p>En virtud de lo dispuesto por la Secretaría de Comercio del Interior mediante Resolución 244/2020, los usuarios vendedores están obligados a informar a los usuarios compradores que los plazos previstos en las garantías contractuales y legales quedan suspendidos por todo el periodo en que no puedan ejercer sus derechos en virtud del Aislamiento Social, Preventivo y Obligatorio dictado por el Decreto 297/2020 y sus modificatorios.</p><br/>
    <p><strong>Impuestos</strong>. Como se menciona anteriormente, Roofstore sólo pone a disposición de los usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar artículos y/o servicios. Roofstore no tiene participación alguna en el proceso de negociación y perfeccionamiento del contrato definitivo entre las partes. Por eso, Roofstore no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p><br/>
    <p>El vendedor acepta que su comprador puede revocar la compra dentro de un plazo de 10 días desde que recibe el producto. Asimismo, el vendedor acepta que los compradores podrán pedir la devolución del producto en los términos de los programas de Compra Protegida, Mercado Puntos y demás Anexos, hasta 30 días después de la recepción del producto. En cualquiera de los mencionados casos, el vendedor deberá aceptar la devolución del producto vendido y deberá hacerse cargo de los gastos que esto conlleve, incluyendo los costos de envío que fueren necesarios. En la categoría de Servicios, el vendedor acepta que el precio será reintegrado a su comprador cuando el servicio contratado no sea efectivamente prestado o sea cancelado hasta la fecha en que debió prestarse. Roofstore podrá debitar estos costos de la cuenta de RoofPay del vendedor.</p><br/>
    <p>Roofstore podrá disponibilizar etiquetas de envíos para que el comprador realice la devolución y debitar el costo de las misma de la cuenta de RoofPay del vendedor.</p><br/>
    <h2>07 - Prohibiciones</h2><br/>
    <p>Los usuarios no podrán: (a) manipular los precios de los artículos; (b) mantener cualquier tipo de comunicación por otro medio distinto al servicio de mensajería que ofrece Roofstore (incluyendo mails, redes sociales, WhatsApp, etc) ya sea durante la oferta del bien o con posterioridad a ella, salvo en la sección de Preguntas y Respuestas y en las categorías Autos, Motos y Otros, Servicios e Inmuebles y Propiedades que así lo permitan; (c) dar a conocer sus datos personales o de otros usuarios a través de la sección de Preguntas y Respuestas y/o por algún otro medio (incluyendo pero sin limitar Twitter, Facebook y/ o cualquier otra red social), salvo en las categorías Autos, Motos y Otros e Inmuebles y Propiedades que así lo permitan; (d) aceptar datos personales proporcionados por otros usuarios a través de la sección de Preguntas y Respuestas y/o algún otro medio (incluyendo pero sin limitar Twitter, Facebook y/o cualquier otra red social); (e) publicar o vender artículos prohibidos por los Términos y Condiciones Generales, demás políticas de Roofstore o leyes vigentes; (f) insultar, discriminar o agredir a otros Usuarios, colaboradores de Roofstore o cualquier persona que esté relacionada a los servicios que Roofstore presta en su plataforma; (g) utilizar su reputación, calificaciones o comentarios recibidos en el sitio de Roofstore en cualquier ámbito fuera de Roofstore; (h) publicar artículos idénticos en más de una publicación.</p><br/>
    <p>Este tipo de actividades será investigado por Roofstore y el infractor podrá ser sancionado con la suspensión o cancelación de la oferta e incluso de su inscripción como usuario de Roofstore y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuración de delitos o contravenciones o los perjuicios civiles que pueda causar a los usuarios oferentes.</p><br/>
    <h2>08 - Violaciones del Sistema o Bases de Datos</h2><br/>
    <p>No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de Roofstore como en las ofertas, descripciones, cuentas o bases de datos de Roofstore. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.</p><br/>
    <h2>09 - Sanciones. Suspensión de operaciones</h2><br/>
    <p>Sin perjuicio de otras medidas, Roofstore podrá advertir, suspender en forma temporal o definitivamente la Cuenta de un Usuario o una publicación, aplicar una sanción que impacte negativamente en la reputación de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestación de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones Generales y demás políticas de Roofstore; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de Roofstore en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea; (e) Roofstore entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las publicó, para Roofstore o para los demás Usuarios en general. En el caso de la suspensión de un Usuario, sea temporal o definitiva, todos los artículos que tuviera publicados serán removidos del sistema.</p><br/>
    <h2>10 - Responsabilidad</h2> <br/>
    <p>Roofstore pone a disposición de los Usuarios un espacio virtual que les permite ponerse en comunicación para ofrecer, vender y/o comprar bienes y servicios.</p> <br/>
    <p>Son los Usuarios Vendedores quienes utilizan Roofstore para publicar sus productos y servicios, y definir las condiciones de su oferta (producto o servicio ofrecido, precio, descripción, fotos, calidad, cantidad, integridad, etc.).</p>
    <p>En todos los casos, al ser los Usuarios Vendedores los propietarios de los productos publicados y quienes los ofrecen para su venta, serán responsables por la existencia, calidad, cantidad, integridad o legitimidad de los productos o servicios que ofrecen, y mantendrán indemnes a Roofstore por las eventuales acciones o reclamaciones que pudiesen surgir con motivo de una oferta o transacción.</p><br/>
    <h2>11 - Alcance de los servicios de Roofstore</h2><br/>
    <p>Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre Roofstore y el usuario. El usuario reconoce y acepta que Roofstore no es parte en ninguna operación, ni tiene control alguno sobre la calidad, seguridad o legalidad de los bienes y servicios anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar artículos. Roofstore no puede asegurar que un usuario completará una operación ni podrá verificar la identidad o datos personales ingresados por los usuarios. Roofstore no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia o contratos que el usuario celebre con dichos terceros o con otros usuarios.</p><br/>
    <p>De igual forma, el usuario reconoce y acepta que Roofstore no es parte, no interviene ni tiene control alguno sobre los servicios de protección extendida que son comercializados y prestados en forma exclusiva por Assurant Services Argentina S.A.</p><br/>
    <h2>12 - Fallas en el sistema</h2><br/>
    <p>Roofstore no se responsabiliza por cualquier daño, perjuicio o pérdida al usuario causados por fallas en el sistema, en el servidor o en Internet. Roofstore tampoco será responsable por cualquier virus que pudiera infectar el equipo del usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet. Roofstore no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a Roofstore; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. Roofstore no será responsable por ningún error u omisión contenidos en su sitio web.</p><br/>
    <h2>13 - Tarifas. Facturación</h2><br/>
    <p>El usuario vendedor solo deberá pagar a Roofstore un costo por la venta cuando la operación se concrete, o si no la cancela antes de los 21 días después de recibir la oferta. Para el caso correspondiente a la categoría Autos, Motos y Otros, Servicios e Inmuebles, el usuario solamente deberá pagar a Roofstore únicamente un costo por publicar, salvo en aquellos Servicios que permitan la contratación en el Sitio y sujeto a la modalidad de publicación elegida.</p><br/>
    <p>Roofstore se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido.</p><br/>
    <p>Roofstore se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual será notificado a los Usuarios, en la forma establecida en la Cláusula 3. Sin embargo, Roofstore podrá modificar temporalmente la Política de Tarifas y las tarifas por sus servicios por razón de promociones, siendo efectivas estas modificaciones cuando se haga pública la promoción o se realice el anuncio.</p><br/>
    <p>En caso de haberse facturado cargos que no hubiesen correspondido, el usuario deberá comunicarse con nuestro equipo de Atención al Cliente para resolver dicha cuestión.</p><br/>
    <p>Conoce más sobre nuestras <TextLink url={'/'} className={'txt-blue'} children={"Políticas de Facturación"}></TextLink>.</p><br/>
    <h2>14 - Sistema de reputación</h2><br/>
    <p>Debido a que la verificación de la identidad de los Usuarios en Internet es difícil, Roofstore no puede confirmar ni confirma la identidad pretendida de cada Usuario. Por ello el Usuario Vendedor cuenta con un sistema de reputación de Usuarios que es actualizado periódicamente en base a datos vinculados con su actividad en el sitio. Este sistema de reputación, además constará de un espacio donde los Usuarios compradores podrán hacer comentarios sobre la experiencia de compra. Dichos comentarios serán incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan.</p><br/>
    <p>Roofstore no tiene obligación de verificar la veracidad o exactitud de los mismos y NO se responsabiliza por los dichos allí vertidos por cualquier Usuario, por las ofertas de compras o ventas que los Usuarios realicen teniéndolos en cuenta o por la confianza depositada en las opiniones de los compradores o por cualquier otro comentario expresado dentro del sitio o a través de cualquier otro medio incluido el correo electrónico. Roofstore se reserva el derecho de editar y/o eliminar aquellos comentarios que sean considerados inadecuados u ofensivos. Roofstore mantiene el derecho de excluir a aquellos Usuarios que sean objeto de comentarios negativos provenientes de fuentes distintas.</p><br/>
    <h2>15 - Propiedad intelectual - Licencia - Enlaces</h2><br/>
    <p>Roofstore y/o sus sociedades controlantes, controladas, filiales o subsidiarias se reservan todos los derechos, incluyendo los derechos de propiedad intelectual e industrial, asociados con los servicios de Roofstore, sus sitios web, los contenidos de sus pantallas, programas, bases de datos, redes, códigos, desarrollo, software, arquitectura, hardware, contenidos, información, tecnología, fases de integración, funcionalidades, dominios, archivos que permiten al Usuario acceder y crear su Cuenta, herramientas de venta, marcas, patentes, derechos de autor, diseños y modelos industriales, nombres comerciales, entre otros, y declara que están protegidos por leyes nacionales e internacionales vigentes.</p><br/>
    <p>En ningún caso se entenderá que el Usuario tendrá algún tipo de derecho sobre los mismos excepto para utilizar el servicio de Roofstore conforme a lo previsto en estos Términos y Condiciones Generales. El uso indebido o contrario a la normativa vigente de los derechos de propiedad intelectual e industrial de Roofstore, así como su reproducción total o parcial, queda prohibido, salvo autorización expresa y por escrito de Roofstore.</p><br/>
    <p>Los Usuarios tampoco podrán comunicar que los productos o servicios que ofrecen son patrocinados, promovidos, producidos, ofrecidos y/o vendidos por Roofstore y deberán abstenerse de realizar cualquier acto que pudiera causar un daño, pérdida de reputación, o disminución del valor de los derechos de propiedad intelectual e industrial de Roofstore.</p><br/>
    <p>El sitio puede contener enlaces a sitios web de terceros. En virtud que Roofstore no tiene control sobre tales sitios, no será responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por daños o pérdidas ocasionadas por la utilización de éstos, causados directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relación, aprobación, respaldo de Roofstore con dichos sitios y sus contenidos.</p> <br/>
    <h2>16 - Indemnidad</h2><br/>
    <p >El Usuario mantendrá indemne a Roofstore, así como a sus filiales, empresas controladas y/o controlantes, funcionarios, directivos, sucesores, administradores, representantes y empleados, por cualquier reclamo iniciado por otros Usuarios, terceros o por cualquier Organismo, relacionado con sus actividades en el Sitio, el cumplimiento y/o el incumplimiento de los Términos y Condiciones Generales o demás Políticas, así como respecto de cualquier violación de leyes o derechos de terceros.</p><br/>
    <p>A tal fin, el Usuario faculta a Roofstore a: i) intervenir y representarlo en dichos reclamos, pudiendo celebrar los acuerdos transaccionales que considere oportunos y que tiendan a evitar mayores costos y/o evitar eventuales contingencias sin limitación, en su nombre y representación;ii) retener y debitar de su Cuenta de RoofPay y/o de la(s) cuenta(s) bancaria(s) registrada(s) en la Cuenta RoofPay los fondos existentes y/o futuros para recuperar cualquier gasto incurrido en relación a los supuestos del párrafo anterior, los cuales podrán incluir, entre otros, los honorarios de los letrados intervinientes y las costas judiciales en una cantidad razonable, y/o iii) generar débitos específicos en su facturación.</p><br/>
    <h2>17 - Anexos</h2><br/>
    <p>Forman parte integral e inseparable de los Términos y Condiciones Generales, los siguientes documentos y/o secciones de Roofstore incorporados por referencia, donde se detallan políticas y/o Términos y Condiciones de diferentes servicios ofrecidos en el sitio. Los mismos se podrán consultar dentro del sitio mediante el enlace abajo provisto o accediendo directamente a las páginas correspondientes:</p>
    <div className="row">
        <div className="col">
            <ul>
                <li><Link to="/" className={'txt-blue'} >Brand Protection Program</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Artículos prohibidos</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Artículos que violan derechos de propiedad intelectual</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Políticas de publicación</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Política de privacidad</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Política de elección de apodo</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Tarifas y facturación</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Sistema de reputación</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Programa de Roofleaders</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Tiendas oficiales</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Inhabilitación o suspensión de usuarios</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de contratación de Roofstore publicidad</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de RoofPay</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de Roofshipping</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de Roofshipping Flex</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de Roofshipping Full</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de uso de Roofshop</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de uso de Mercado Puntos</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones para el Programa Roofstore Solidario</Link></li><br/>
                <li><Link to="/" className={'txt-blue'}>Términos y condiciones del beneficio "Codo a Codo con las PYMES"</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Compra Protegida con RoofPay</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Reserva de vehículos</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Sistema de opiniones de servicios</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Sistema de opiniones de productos</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Sistema de opiniones de automóviles</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones para la compraventa internacional</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Publicaciones de catálogo</Link></li><br/>
                <li><Link to="/" className={'txt-blue'}>Términos y condiciones para la adhesión del Programa "Ahora 12"</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Productos vendidos por Roofstore</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y condiciones de préstamos personales</Link></li><br/>
                <li><Link to="/" className={'txt-blue'} >Términos y Condiciones de compras y pagos con RoofCredit</Link></li>
            </ul>
        </div>
       
    </div>
    <br/>
    <h2>18 - Jurisdicción y Ley Aplicable</h2><br/>
    <p> Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Argentina.</p><br/>
    <p >Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida ante la Justicia Nacional Ordinaria salvo disposición específica de normas de Orden Público, como por ejemplo la Ley de Defensa del Consumidor (o normativa vinculada) en los casos en los que ésta sea aplicable.<br/></p>
    <h2>19 - Domicilio</h2><br/>
    <p>Se fija como domicilio de Roofstore, San Francisco, Cordoba, República Argentina.</p><br/>
    <p>Si tienes alguna duda sobre los Términos y Condiciones Generales o demás políticas y principios que rigen Roofstore consulta nuestra página de <TextLink url={'/'} className={'txt-blue'} children={"Ayuda"}></TextLink>.</p>

</div>


export default info